name: Generate Repo Diagram

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output folder
        run: mkdir -p images

      - name: Generate diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "images/diagram.svg"
          excluded_paths: "dist,node_modules"
          should_push: true
          commit_message: "Auto-added repo diagram [skip ci]"
          branch: main

